export type ObjectType = { name: string; passThrough: boolean };

export const ObjectTypes: Record<number, ObjectType> = {
  // Basic blocks
  0: { name: "Null", passThrough: true },
  1: { name: "Air", passThrough: true },
  2: { name: "Water", passThrough: true },
  3: { name: "Bedrock", passThrough: false },
  4: { name: "Stone", passThrough: false },
  5: { name: "Deepslate", passThrough: false },
  6: { name: "Granite", passThrough: false },
  7: { name: "Tuff", passThrough: false },
  8: { name: "Calcite", passThrough: false },
  9: { name: "Basalt", passThrough: false },
  10: { name: "SmoothBasalt", passThrough: false },
  11: { name: "Andesite", passThrough: false },
  12: { name: "Diorite", passThrough: false },
  13: { name: "Cobblestone", passThrough: false },
  14: { name: "MossyCobblestone", passThrough: false },
  15: { name: "Obsidian", passThrough: false },
  16: { name: "Dripstone", passThrough: false },
  17: { name: "Blackstone", passThrough: false },
  18: { name: "CobbledDeepslate", passThrough: false },
  19: { name: "Amethyst", passThrough: false },
  20: { name: "Glowstone", passThrough: false },
  21: { name: "Grass", passThrough: false },
  22: { name: "Dirt", passThrough: false },
  23: { name: "Moss", passThrough: false },
  24: { name: "Podzol", passThrough: false },
  25: { name: "DirtPath", passThrough: false },
  26: { name: "Mud", passThrough: false },
  27: { name: "PackedMud", passThrough: false },
  28: { name: "Farmland", passThrough: false },
  29: { name: "WetFarmland", passThrough: false },
  30: { name: "UnrevealedOre", passThrough: false },
  31: { name: "Gravel", passThrough: false },
  32: { name: "Sand", passThrough: false },
  33: { name: "RedSand", passThrough: false },
  34: { name: "Sandstone", passThrough: false },
  35: { name: "RedSandstone", passThrough: false },
  36: { name: "Clay", passThrough: false },
  37: { name: "Terracotta", passThrough: false },
  38: { name: "BrownTerracotta", passThrough: false },
  39: { name: "OrangeTerracotta", passThrough: false },
  40: { name: "WhiteTerracotta", passThrough: false },
  41: { name: "LightGrayTerracotta", passThrough: false },
  42: { name: "YellowTerracotta", passThrough: false },
  43: { name: "RedTerracotta", passThrough: false },
  44: { name: "LightBlueTerracotta", passThrough: false },
  45: { name: "CyanTerracotta", passThrough: false },
  46: { name: "BlackTerracotta", passThrough: false },
  47: { name: "PurpleTerracotta", passThrough: false },
  48: { name: "BlueTerracotta", passThrough: false },
  49: { name: "MagentaTerracotta", passThrough: false },

  // Wood blocks
  50: { name: "OakLog", passThrough: false },
  51: { name: "BirchLog", passThrough: false },
  52: { name: "JungleLog", passThrough: false },
  53: { name: "SakuraLog", passThrough: false },
  54: { name: "AcaciaLog", passThrough: false },
  55: { name: "SpruceLog", passThrough: false },
  56: { name: "DarkOakLog", passThrough: false },
  57: { name: "MangroveLog", passThrough: false },
  58: { name: "OakLeaf", passThrough: false },
  59: { name: "BirchLeaf", passThrough: false },
  60: { name: "JungleLeaf", passThrough: false },
  61: { name: "SakuraLeaf", passThrough: false },
  62: { name: "SpruceLeaf", passThrough: false },
  63: { name: "AcaciaLeaf", passThrough: false },
  64: { name: "DarkOakLeaf", passThrough: false },
  65: { name: "AzaleaLeaf", passThrough: false },
  66: { name: "FloweringAzaleaLeaf", passThrough: false },
  67: { name: "MangroveLeaf", passThrough: false },
  68: { name: "MangroveRoots", passThrough: false },
  69: { name: "MuddyMangroveRoots", passThrough: false },

  // Plants and flowers (passthrough)
  70: { name: "AzaleaFlower", passThrough: true },
  71: { name: "BellFlower", passThrough: true },
  72: { name: "DandelionFlower", passThrough: true },
  73: { name: "DaylilyFlower", passThrough: true },
  74: { name: "LilacFlower", passThrough: true },
  75: { name: "RoseFlower", passThrough: true },
  76: { name: "FireFlower", passThrough: true },
  77: { name: "MorninggloryFlower", passThrough: true },
  78: { name: "PeonyFlower", passThrough: true },
  79: { name: "Ultraviolet", passThrough: true },
  80: { name: "SunFlower", passThrough: true },
  81: { name: "FlyTrap", passThrough: true },
  82: { name: "FescueGrass", passThrough: true },
  83: { name: "SwitchGrass", passThrough: true },
  84: { name: "VinesBush", passThrough: true },
  85: { name: "IvyVine", passThrough: true },
  86: { name: "HempBush", passThrough: true },
  87: { name: "GoldenMushroom", passThrough: true },
  88: { name: "RedMushroom", passThrough: true },
  89: { name: "CoffeeBush", passThrough: true },
  90: { name: "StrawberryBush", passThrough: true },
  91: { name: "RaspberryBush", passThrough: true },
  92: { name: "Wheat", passThrough: true },
  93: { name: "CottonBush", passThrough: true },
  94: { name: "Pumpkin", passThrough: false },
  95: { name: "Melon", passThrough: false },
  96: { name: "RedMushroomBlock", passThrough: false },
  97: { name: "BrownMushroomBlock", passThrough: false },
  98: { name: "MushroomStem", passThrough: false },
  99: { name: "BambooBush", passThrough: true },
  100: { name: "Cactus", passThrough: false },

  // Water blocks
  101: { name: "Coral", passThrough: true },
  102: { name: "SeaAnemone", passThrough: true },
  103: { name: "Algae", passThrough: true },
  104: { name: "HornCoralBlock", passThrough: false },
  105: { name: "FireCoralBlock", passThrough: false },
  106: { name: "TubeCoralBlock", passThrough: false },
  107: { name: "BubbleCoralBlock", passThrough: false },
  108: { name: "BrainCoralBlock", passThrough: false },

  // Environment
  109: { name: "Snow", passThrough: false },
  110: { name: "Ice", passThrough: false },
  111: { name: "Lava", passThrough: false },
  112: { name: "SpiderWeb", passThrough: false },
  113: { name: "Bone", passThrough: false },

  // Ores
  114: { name: "CoalOre", passThrough: false },
  115: { name: "CopperOre", passThrough: false },
  116: { name: "IronOre", passThrough: false },
  117: { name: "GoldOre", passThrough: false },
  118: { name: "DiamondOre", passThrough: false },
  119: { name: "NeptuniumOre", passThrough: false },

  // Functional blocks
  120: { name: "TextSign", passThrough: false },
  121: { name: "OakPlanks", passThrough: false },
  122: { name: "BirchPlanks", passThrough: false },
  123: { name: "JunglePlanks", passThrough: false },
  124: { name: "SakuraPlanks", passThrough: false },
  125: { name: "SprucePlanks", passThrough: false },
  126: { name: "AcaciaPlanks", passThrough: false },
  127: { name: "DarkOakPlanks", passThrough: false },
  128: { name: "MangrovePlanks", passThrough: false },
  129: { name: "CopperBlock", passThrough: false },
  130: { name: "IronBlock", passThrough: false },
  131: { name: "GoldBlock", passThrough: false },
  132: { name: "DiamondBlock", passThrough: false },
  133: { name: "NeptuniumBlock", passThrough: false },

  // Seeds and saplings (passthrough)
  134: { name: "WheatSeed", passThrough: true },
  135: { name: "PumpkinSeed", passThrough: true },
  136: { name: "MelonSeed", passThrough: true },
  137: { name: "OakSapling", passThrough: true },
  138: { name: "BirchSapling", passThrough: true },
  139: { name: "JungleSapling", passThrough: true },
  140: { name: "SakuraSapling", passThrough: true },
  141: { name: "AcaciaSapling", passThrough: true },
  142: { name: "SpruceSapling", passThrough: true },
  143: { name: "DarkOakSapling", passThrough: true },
  144: { name: "MangroveSapling", passThrough: true },

  // Special blocks
  145: { name: "ForceField", passThrough: false },
  146: { name: "Chest", passThrough: false },
  147: { name: "SpawnTile", passThrough: false },
  148: { name: "Bed", passThrough: false },
  149: { name: "Workbench", passThrough: false },
  150: { name: "Powerstone", passThrough: false },
  151: { name: "Furnace", passThrough: false },
  152: { name: "Torch", passThrough: true },

  // Tools and items (high IDs)
  32768: { name: "WoodenPick", passThrough: false },
  32769: { name: "CopperPick", passThrough: false },
  32770: { name: "IronPick", passThrough: false },
  32771: { name: "GoldPick", passThrough: false },
  32772: { name: "DiamondPick", passThrough: false },
  32773: { name: "NeptuniumPick", passThrough: false },
  32774: { name: "WoodenAxe", passThrough: false },
  32775: { name: "CopperAxe", passThrough: false },
  32776: { name: "IronAxe", passThrough: false },
  32777: { name: "GoldAxe", passThrough: false },
  32778: { name: "DiamondAxe", passThrough: false },
  32779: { name: "NeptuniumAxe", passThrough: false },
  32780: { name: "WoodenWhacker", passThrough: false },
  32781: { name: "CopperWhacker", passThrough: false },
  32782: { name: "IronWhacker", passThrough: false },
  32783: { name: "WoodenHoe", passThrough: false },
  32784: { name: "GoldBar", passThrough: false },
  32785: { name: "IronBar", passThrough: false },
  32786: { name: "Diamond", passThrough: false },
  32787: { name: "NeptuniumBar", passThrough: false },
  32788: { name: "Bucket", passThrough: false },
  32789: { name: "WaterBucket", passThrough: false },
  32790: { name: "WheatSlop", passThrough: false },
  32791: { name: "PumpkinSoup", passThrough: false },
  32792: { name: "MelonSmoothie", passThrough: false },
  32793: { name: "Battery", passThrough: false },
  32794: { name: "AnyLog", passThrough: false },
  32795: { name: "AnyPlank", passThrough: false },
  32796: { name: "AnyTerracotta", passThrough: false },
  32797: { name: "AnyLeaf", passThrough: false },
  32798: { name: "Player", passThrough: false },
  32799: { name: "Fragment", passThrough: false },
} as const;

// Helper function to find object ID by name
export function getObjectIdByName(name: string): number | undefined {
  const entry = Object.entries(ObjectTypes).find(
    ([_, obj]) => obj.name === name
  );
  return entry ? Number(entry[0]) : undefined;
}
